version: '3'
services:
    web:
        image: nginx:1.15
        volumes:
            - ./.docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./log/nginx:/var/log/nginx
            - ..:/var/www/html
        ports:
            - 80:80
        restart: always
        depends_on:
            - php
            - db
    php:
        build: .docker
        restart: always
        volumes:
#            - ./home/ubuntu/.backup:/home/ubuntu/.aws
            - ./.docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./.docker/conf/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ./log/php:/var/log
#            - "./etc/crontabs:/var/spool/cron/crontabs:rw"
            - ..:/var/www/html
#    composer:
#        image: composer
#        volumes:
#            - ..:/app
#        command: install
    db:
        image: postgres:10.1
        restart: always
        command: mkdir /home/ubuntu/.backup/
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - 5432:5432
        volumes:
            - ./home/ubuntu/.backup:/home/ubuntu/.backup
            - ./.docker/conf/postgres-init/:/docker-entrypoint-initdb.d/
            - ./pg:/var/lib/postgresql/data
